config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  get 'users/new'
  get 'users/profile', as: 'user_root'

  get 'fetch_people', to: 'people#fetch', as: 'fetch_people'

  resources :vehicles, only: [:index, :show]
  resources :starships, only: [:index, :show]
  resources :species, only: [:index, :show]
  resources :planets, only: [:index, :show]
  resources :people, only: [:index, :show]
  resources :films, only: [:index, :show]

  root 'static_pages#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
      can :access, :rails_admin
      can :dashboard
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  has_and_belongs_to_many :people
  has_and_belongs_to_many :planets
  has_and_belongs_to_many :species
  has_and_belongs_to_many :starships
  has_and_belongs_to_many :vehicles

  has_attached_file :poster,
                    styles: { medium: '300x300>', thumb: '100x100>' },
                    default_url: 'http://placehold.it/300x300'

  validates_attachment_content_type :poster, content_type: %r{\Aimage\/.*\z}

  attr_accessor :delete_poster
  before_validation { self.poster.clear if self.delete_poster == '1' }

  def name
    title
  end
end

app/models/person.rb
class Person < ApplicationRecord
  default_scope { order :id }

  has_and_belongs_to_many :films
  has_and_belongs_to_many :species
  has_and_belongs_to_many :starships
  has_and_belongs_to_many :vehicles
  belongs_to :planet

  PER_PAGE = [10, 20, 50].freeze
  PER_PAGE_DEFAULT = PER_PAGE[0]

  def self.page(number, per_page)
    pp = (per_page || PER_PAGE_DEFAULT).to_i
    offset = (number.to_i - 1) * pp
    Person.offset(offset).limit(pp)
  end

  def self.pages_number(per_page)
    pp = (per_page || PER_PAGE_DEFAULT).to_i
    cnt = Person.count
    offset = (cnt % pp).zero? ? 0 : 1
    cnt / pp + offset
  end

end

app/models/planet.rb
class Planet < ApplicationRecord
  has_and_belongs_to_many :films
  has_many :people
  has_many :species
end

app/models/species.rb
class Species < ApplicationRecord
  belongs_to :planet, optional: true
  has_and_belongs_to_many :people
  has_and_belongs_to_many :films
end

app/models/starship.rb
class Starship < ApplicationRecord
  has_and_belongs_to_many :films
  has_and_belongs_to_many :people
end

app/models/user.rb
class User < ApplicationRecord
  # Include devise modules
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable,
         # :lockable,
         # :omniauthable,
         :timeoutable

  ROLES = %i(admin).freeze

  def admin?
    role == 'admin'
  end
end

app/models/veh_class.rb
class VehClass < ApplicationRecord
  has_many :vehicles
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_and_belongs_to_many :films
  has_and_belongs_to_many :people
  belongs_to :veh_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.all.order :episode_id
  end

  def show
    @film = Film.find params[:id]
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :setup, except: :show

  def index
  end

  def fetch
    respond_to :js
  end

  def show
    @person = Person.find params[:id]
  end

  private

  def setup
    @pages_n = Person.pages_number params[:per_page]
    @page = params[:page] || 1 # first page by default
    @people = Person.page @page, params[:per_page]
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def show
    @planet = Planet.find params[:id]
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
    @species = Species.all
  end

  def show
    @species = Species.find params[:id]
  end
end

app/controllers/starships_controller.rb
class StarshipsController < ApplicationController
  def index
    @starships = Starship.all
  end

  def show
    @starship = Starship.find params[:id]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicle.all
  end

  def show
    @vehicle = Vehicle.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Star Wars"
    return base_title if page_title.empty?
    page_title + " | " + base_title
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def page_class(i, active)
    c = 'people-page'
    c += ' active' if i == active.to_i
    c
  end

  def page_sizes
    Person::PER_PAGE
  end
end

app/views/films/index.html.erb
<% provide(:title, 'Films') %>

<h1>Films</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Episode</th>
      <th>Title</th>
      <th>Release date</th>
      <th>Director</th>
      <th>Producer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr class="clickable-row" data-href="<%= film_path(film) %>">
        <td><%= film.episode_id %></td>
        <td><%= film.title %></td>
        <td><%= film.release_date %></td>
        <td><%= film.director %></td>
        <td><%= film.producer %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/films/show.html.erb
<% provide(:title, @film.title) %>

<h1>Episode <%= @film.episode_id %>: <%= @film.title %></h1>
<h2>by <%= @film.director %></h2>

<%= image_tag @film.poster.url %>

<p class="center-justified">
  <%= h(@film.opening_crawl).gsub(/\n/, '<br>').html_safe %>
</p>

<p>
  <strong>Producer:</strong>
  <%= @film.producer %>
  <br>
  <strong>Release date:</strong>
  <%= @film.release_date %>
</p>


<%= render partial: 'shared/spoilers', locals: {
    summaries: %w(Characters Planets Species Starships Vehicles),
    collections: [ @film.people, @film.planets, @film.species, @film.starships, @film.vehicles ]
}%>

app/views/people/_pagination.html.erb
<ul class="pagination">
  <% 1.upto(pages_n) do |i| %>
      <%= content_tag :li, content_tag(:a, i), class: page_class(i, page), value: i %>
  <% end %>
</ul>

app/views/people/_people_table.html.erb
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Gender</th>
    <th>Birth year</th>
    <th>Eye color</th>
    <th>Hair color</th>
    <th>Height</th>
    <th>Mass</th>
    <th>Skin color</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% people.each do |person| %>
      <tr class="clickable-row" data-href="<%= person_path(person) %>">
        <td><%= person.name %></td>
        <td><%= person.gender %></td>
        <td><%= person.birth_year %></td>
        <td><%= person.eye_color %></td>
        <td><%= person.hair_color %></td>
        <td><%= person.height %></td>
        <td><%= person.mass %></td>
        <td><%= person.skin_color %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/people/fetch.js.erb
$("#people_table")
  .html("<%= escape_javascript(render partial: 'people_table', locals: { people: @people } ) %>");
$("#people_pagination")
  .html("<%= escape_javascript(render partial: 'pagination', locals: { pages_n: @pages_n, page: @page } ) %>");

app/views/people/index.html.erb
<% provide(:title, 'People') %>

<h1>People</h1>

<div id="people_table" class="container">
  <%= render partial: 'people_table', locals: { people: @people } %>
</div>

<div id="people_pagination" class="container">
  <%= render partial: 'pagination', locals: { pages_n: @pages_n, page: @page } %>
</div>

<div class="form-group">
  <label for="sel_ppl_per_page">Per page:</label>
  <%= select_tag :per_page,
                 options_for_select( page_sizes.zip page_sizes ),
                 class: 'form-control',
                 id: 'sel_ppl_per_page'
  %>
</div>

app/views/people/show.html.erb
<% provide(:title, @person.name) %>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @person.gender %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @person.birth_year %>
</p>

<p>
  <strong>Skin color:</strong>
  <%= @person.skin_color %>
</p>

<p>
  <strong>Eye color:</strong>
  <%= @person.eye_color %>
</p>

<p>
  <strong>Hair color:</strong>
  <%= @person.hair_color %>
</p>

<p>
  <strong>Height:</strong>
  <%= @person.height %>
</p>

<p>
  <strong>Mass:</strong>
  <%= @person.mass %>
</p>

<p>
  <strong>Homeworld:</strong>
  <%= link_to @person.planet.name, @person.planet %>
</p>


<%= render partial: 'shared/spoilers', locals: {
    summaries: %w(Films Species Starships Vehicles),
    collections: [ @person.films, @person.species, @person.starships, @person.vehicles ]
}%>

app/views/planets/index.html.erb
<% provide(:title, 'Planets') %>

<h1>Planets</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Climate</th>
      <th>Diameter</th>
      <th>Gravity</th>
      <th>Orbital period</th>
      <th>Population</th>
      <th>Rotation period</th>
      <th>Surface water</th>
      <th>Terrain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planets.each do |planet| %>
      <tr class="clickable-row" data-href="<%= planet_path(planet) %>">
        <td><%= planet.name %></td>
        <td><%= planet.climate %></td>
        <td><%= planet.diameter %></td>
        <td><%= planet.gravity %></td>
        <td><%= planet.orbital_period %></td>
        <td><%= planet.population %></td>
        <td><%= planet.rotation_period %></td>
        <td><%= planet.surface_water %></td>
        <td><%= planet.terrain %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/planets/show.html.erb
<% provide(:title, @planet.name) %>

<p>
  <strong>Name:</strong>
  <%= @planet.name %>
</p>

<p>
  <strong>Climate:</strong>
  <%= @planet.climate %>
</p>

<p>
  <strong>Diameter:</strong>
  <%= @planet.diameter %>
</p>

<p>
  <strong>Gravity:</strong>
  <%= @planet.gravity %>
</p>

<p>
  <strong>Orbital period:</strong>
  <%= @planet.orbital_period %>
</p>

<p>
  <strong>Population:</strong>
  <%= @planet.population %>
</p>

<p>
  <strong>Rotation period:</strong>
  <%= @planet.rotation_period %>
</p>

<p>
  <strong>Surface water:</strong>
  <%= @planet.surface_water %>
</p>

<p>
  <strong>Terrain:</strong>
  <%= @planet.terrain %>
</p>

<%= render partial: 'shared/spoilers', locals: {
    summaries: %w(Films Residents),
    collections: [ @planet.films, @planet.people ]
}%>

app/views/species/index.html.erb
<% provide(:title, 'Species') %>

<h1>Species</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Average height</th>
      <th>Average lifespan</th>
      <th>Classification</th>
      <th>Designation</th>
      <th>Eye colors</th>
      <th>Hair colors</th>
      <th>Language</th>
      <th>Skin colors</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @species.each do |species| %>
      <tr class="clickable-row" data-href="<%= species_path(species) %>">
        <td><%= species.name %></td>
        <td><%= species.average_height %></td>
        <td><%= species.average_lifespan %></td>
        <td><%= species.classification %></td>
        <td><%= species.designation %></td>
        <td><%= species.eye_colors %></td>
        <td><%= species.hair_colors %></td>
        <td><%= species.language %></td>
        <td><%= species.skin_colors %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/species/show.html.erb
<% provide(:title, @species.name) %>

<p>
  <strong>Name:</strong>
  <%= @species.name %>
</p>
<p>
  <strong>Average height:</strong>
  <%= @species.average_height %>
</p>

<p>
  <strong>Average lifespan:</strong>
  <%= @species.average_lifespan %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @species.classification %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @species.designation %>
</p>

<p>
  <strong>Eye colors:</strong>
  <%= @species.eye_colors %>
</p>

<p>
  <strong>Hair colors:</strong>
  <%= @species.hair_colors %>
</p>

<p>
  <strong>Language:</strong>
  <%= @species.language %>
</p>

<p>
  <strong>Skin colors:</strong>
  <%= @species.skin_colors %>
</p>

<p>
  <strong>Homeworld:</strong>
  <%= link_to @species.planet.name, @species.planet %>
</p>

<%= render partial: 'shared/spoilers', locals: {
    summaries: %w(Films People),
    collections: [ @species.films, @species.people ]
}%>

app/views/starships/index.html.erb
<% provide(:title, 'Starships') %>

<h1>Starships</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>Starship class</th>
      <th>Consumables</th>
      <th>Crew</th>
      <th>Hyperdrive rating</th>
      <th>Passengers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @starships.each do |starship| %>
      <tr class="clickable-row" data-href="<%= starship_path(starship) %>">
        <td><%= starship.name %></td>
        <td><%= starship.manufacturer %></td>
        <td><%= starship.model %></td>
        <td><%= starship.starship_class %></td>
        <td><%= starship.consumables %></td>
        <td><%= starship.crew %></td>
        <td><%= starship.hyperdrive_rating %></td>
        <td><%= starship.passengers %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/starships/show.html.erb
<% provide(:title, @starship.name) %>

<p>
  <strong>Name:</strong>
  <%= @starship.name %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @starship.manufacturer %>
</p>

<p>
  <strong>Model:</strong>
  <%= @starship.model %>
</p>

<p>
  <strong>Max atmosphering speed:</strong>
  <%= @starship.max_atmosphering_speed %>
</p>


<p>
  <strong>Mglt:</strong>
  <%= @starship.MGLT %>
</p>

<p>
  <strong>Cargo capacity:</strong>
  <%= @starship.cargo_capacity %>
</p>

<p>
  <strong>Consumables:</strong>
  <%= @starship.consumables %>
</p>

<p>
  <strong>Cost in credits:</strong>
  <%= @starship.cost_in_credits %>
</p>

<p>
  <strong>Crew:</strong>
  <%= @starship.crew %>
</p>

<p>
  <strong>Hyperdrive rating:</strong>
  <%= @starship.hyperdrive_rating %>
</p>

<p>
  <strong>Length:</strong>
  <%= @starship.length %>
</p>


<p>
  <strong>Passengers:</strong>
  <%= @starship.passengers %>
</p>

<p>
  <strong>Starship class:</strong>
  <%= @starship.starship_class %>
</p>

<%= render partial: 'shared/spoilers', locals: {
    summaries: %w(Films Pilots),
    collections: [ @starship.films, @starship.people ]
}%>

app/views/static_pages/_panel.html.erb
<div class="col-sm-4">
  <%= link_to path do %>
      <div class="panel panel-default">
        <div class="panel-heading"><%= title %></div>
        <div class="panel-body"><%=	image_tag img, class: 'img-responsive' %></div>
      </div>
  <% end %>
</div>

app/views/static_pages/index.html.erb
<div class="container">
  <div class="row">
    <%= render partial: 'panel', locals: { path: films_path, title: 'Films', img: 'sw.jpg' } %>
    <%= render partial: 'panel', locals: { path: people_path, title: 'People', img: 'sw.jpg' } %>
    <%= render partial: 'panel', locals: { path: planets_path, title: 'Planets', img: 'sw.jpg' } %>
  </div>
</div><br>

<div class="container">
  <div class="row">
    <%= render partial: 'panel', locals: { path: species_index_path, title: 'Species', img: 'sw.jpg' } %>
    <%= render partial: 'panel', locals: { path: starships_path, title: 'Starships', img: 'sw.jpg' } %>
    <%= render partial: 'panel', locals: { path: vehicles_path, title: 'Vehicles', img: 'sw.jpg' } %>
  </div>
</div><br><br>

app/views/users/profile.html.erb
<h1>Profile</h1>
<p><%= current_user.email %></p>

app/views/vehicles/index.html.erb
<% provide(:title, 'Vehicles') %>

<h1>Vehicles</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>Vehicle class</th>
      <th>Cargo capacity</th>
      <th>Consumables</th>
      <th>Crew</th>
      <th>Length</th>
      <th>Passengers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr class="clickable-row" data-href="<%= vehicle_path(vehicle) %>">
        <td><%= vehicle.name %></td>
        <td><%= vehicle.manufacturer %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.veh_class.name %></td>
        <td><%= vehicle.cargo_capacity %></td>
        <td><%= vehicle.consumables %></td>
        <td><%= vehicle.crew %></td>
        <td><%= vehicle.length %></td>
        <td><%= vehicle.passengers %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vehicles/show.html.erb
<% provide(:title, @vehicle.name) %>

<p>
  <strong>Name:</strong>
  <%= @vehicle.name %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @vehicle.manufacturer %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Vehicle class:</strong>
  <%= @vehicle.veh_class.name %>
</p>

<p>
  <strong>Cargo capacity:</strong>
  <%= @vehicle.cargo_capacity %>
</p>

<p>
  <strong>Consumables:</strong>
  <%= @vehicle.consumables %>
</p>

<p>
  <strong>Cost in credits:</strong>
  <%= @vehicle.cost_in_credits %>
</p>

<p>
  <strong>Crew:</strong>
  <%= @vehicle.crew %>
</p>

<p>
  <strong>Length:</strong>
  <%= @vehicle.length %>
</p>

<p>
  <strong>Max atmosphering speed:</strong>
  <%= @vehicle.max_atmosphering_speed %>
</p>


<p>
  <strong>Passengers:</strong>
  <%= @vehicle.passengers %>
</p>


<%= render partial: 'shared/spoilers', locals: {
    summaries: %w(Films Pilots),
    collections: [ @vehicle.films, @vehicle.people ]
}%>