config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  get 'users/new'
  get 'users/profile', as: 'user_root'

  get 'fetch_people', to: 'people#fetch', as: 'fetch_people'

  resources :vehicles, only: [:index, :show]
  resources :starships, only: [:index, :show]
  resources :species, only: [:index, :show]
  resources :planets, only: [:index, :show]
  resources :people, only: [:index, :show]
  resources :films, only: [:index, :show]

  root 'static_pages#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
      can :access, :rails_admin
      can :dashboard
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  has_and_belongs_to_many :people
  has_and_belongs_to_many :planets
  has_and_belongs_to_many :species
  has_and_belongs_to_many :starships
  has_and_belongs_to_many :vehicles

  has_attached_file :poster,
                    styles: { medium: '300x300>', thumb: '100x100>' },
                    default_url: 'http://placehold.it/300x300'

  validates_attachment_content_type :poster, content_type: %r{\Aimage\/.*\z}

  attr_accessor :delete_poster
  before_validation { self.poster.clear if self.delete_poster == '1' }

  def name
    title
  end
end

app/models/person.rb
class Person < ApplicationRecord
  default_scope { order :id }

  has_and_belongs_to_many :films
  has_and_belongs_to_many :species
  has_and_belongs_to_many :starships
  has_and_belongs_to_many :vehicles
  belongs_to :planet

  PER_PAGE = [10, 20, 50].freeze
  PER_PAGE_DEFAULT = PER_PAGE[0]

  def self.page(number, per_page)
    pp = (per_page || PER_PAGE_DEFAULT).to_i
    offset = (number.to_i - 1) * pp
    Person.offset(offset).limit(pp)
  end

  def self.pages_number(per_page)
    pp = (per_page || PER_PAGE_DEFAULT).to_i
    cnt = Person.count
    offset = (cnt % pp).zero? ? 0 : 1
    cnt / pp + offset
  end

end

app/models/planet.rb
class Planet < ApplicationRecord
  has_and_belongs_to_many :films
  has_many :people
  has_many :species
end

app/models/species.rb
class Species < ApplicationRecord
  belongs_to :planet, optional: true
  has_and_belongs_to_many :people
  has_and_belongs_to_many :films
end

app/models/starship.rb
class Starship < ApplicationRecord
  has_and_belongs_to_many :films
  has_and_belongs_to_many :people
end

app/models/user.rb
class User < ApplicationRecord
  # Include devise modules
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable,
         # :lockable,
         # :omniauthable,
         :timeoutable

  ROLES = %i(admin).freeze

  def admin?
    role == 'admin'
  end
end

app/models/veh_class.rb
class VehClass < ApplicationRecord
  has_many :vehicles
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_and_belongs_to_many :films
  has_and_belongs_to_many :people
  belongs_to :veh_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.all.order :episode_id
  end

  def show
    @film = Film.find params[:id]
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :setup, except: :show

  def index
  end

  def fetch
    respond_to :js
  end

  def show
    @person = Person.find params[:id]
  end

  private

  def setup
    @pages_n = Person.pages_number params[:per_page]
    @page = params[:page] || 1 # first page by default
    @people = Person.page @page, params[:per_page]
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def show
    @planet = Planet.find params[:id]
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
    @species = Species.all
  end

  def show
    @species = Species.find params[:id]
  end
end

app/controllers/starships_controller.rb
class StarshipsController < ApplicationController
  def index
    @starships = Starship.all
  end

  def show
    @starship = Starship.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicle.all
  end

  def show
    @vehicle = Vehicle.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Star Wars"
    return base_title if page_title.empty?
    page_title + " | " + base_title
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def page_class(i, active)
    c = 'people-page'
    c += ' active' if i == active.to_i
    c
  end

  def page_sizes
    Person::PER_PAGE
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Star Wars", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Films", films_path %></li>
        <li><%= link_to "People", people_path %></li>
        <li><%= link_to "Planets", planets_path %></li>
        <li><%= link_to "Species", species_index_path %></li>
        <li><%= link_to "Starships", starships_path %></li>
        <li><%= link_to "Vehicles", vehicles_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to "Profile", user_root_path %></li>
            <li><%=	link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Log in | Sign up", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_spoilers.html.erb
<% summaries.zip(collections).each do |summary, collection| %>
  <details>
    <summary><%= summary %></summary>
    <ul>
      <% collection.each do |item| %>
          <li><%= link_to item.name, item %></li>
      <% end %>
    </ul>
  </details>
<% end %>